# Generated by Django 6.0.3 on 2026-04-17 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID externo de referencia en el sistema cliente', max_length=100)),
                ('document_name', models.CharField(help_text='Nombre amigable del documento', max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('PENDING', 'Pendiente de firma'), ('SIGNED', 'Firmado'), ('REFUSED', 'Rechazado por firmante'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='CREATED', max_length=20)),
                ('document_hash', models.CharField(blank=True, help_text='Hash SHA-256 del documento (trazabilidad)', max_length=64, null=True)),
                ('document_url', models.URLField(help_text='URL pública del documento a firmar')),
                ('document_version', models.CharField(default='1.0', help_text='Versión del documento', max_length=20)),
                ('signer_name', models.CharField(help_text='Nombre del firmante', max_length=255)),
                ('signer_email', models.EmailField(help_text='Email del firmante', max_length=254)),
                ('signer_ip', models.GenericIPAddressField(blank=True, help_text='IP del firmante al momento de firmar', null=True)),
                ('provider', models.CharField(default='zapsign', help_text='Proveedor de firma utilizado', max_length=50)),
                ('provider_document_id', models.CharField(blank=True, db_index=True, help_text='ID único del documento en el proveedor', max_length=200, null=True, unique=True)),
                ('provider_sign_url', models.URLField(blank=True, help_text='URL de firma proporcionada por el proveedor', max_length=1000, null=True)),
                ('provider_signed_document_url', models.URLField(blank=True, help_text='URL del documento firmado en el proveedor', max_length=1000, null=True)),
                ('provider_status', models.CharField(blank=True, help_text='Estado reportado por el proveedor', max_length=50, null=True)),
                ('document_file', models.FileField(help_text='Archivo original del documento', upload_to='signature_requests/%Y/%m/')),
                ('signed_document_file', models.FileField(blank=True, help_text='Documento descargado después de firmar', null=True, upload_to='signature_requests_signed/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Cuándo se envió para firma', null=True)),
                ('signed_at', models.DateTimeField(blank=True, help_text='Cuándo se firmó (timestamp del proveedor)', null=True)),
                ('refused_at', models.DateTimeField(blank=True, help_text='Cuándo fue rechazado', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del cliente')),
                ('provider_webhook_payload', models.JSONField(blank=True, default=dict, help_text='Payload completo del último webhook del proveedor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Firma',
                'verbose_name_plural': 'Solicitudes de Firma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('document_created', 'Documento creado'), ('document_sent', 'Documento enviado'), ('document_viewed', 'Documento visualizado'), ('document_signed', 'Documento firmado'), ('document_refused', 'Documento rechazado'), ('document_expired', 'Documento expirado'), ('signer_completed', 'Firmante completó'), ('webhook_received', 'Webhook recibido')], max_length=50)),
                ('provider_event_type', models.CharField(help_text='Tipo de evento reportado por el proveedor (ej: doc_signed)', max_length=100)),
                ('payload', models.JSONField(help_text='Datos completos del evento/webhook')),
                ('http_headers', models.JSONField(default=dict, help_text='Headers HTTP recibidos')),
                ('http_ip_address', models.GenericIPAddressField(help_text='IP desde donde vino el evento')),
                ('signature_valid', models.BooleanField(default=False, help_text='Si la firma/HMAC fue validada correctamente')),
                ('processed', models.BooleanField(default=False, help_text='Si el evento fue procesado exitosamente')),
                ('processing_error', models.TextField(blank=True, help_text='Error si el procesamiento falló', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signature_service.signaturerequest')),
            ],
            options={
                'verbose_name': 'Evento de Firma',
                'verbose_name_plural': 'Eventos de Firma',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['provider_document_id'], name='signature_s_provide_78e985_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['status', 'created_at'], name='signature_s_status_6779a2_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['signer_email'], name='signature_s_signer__aa4f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['external_id'], name='signature_s_externa_4dd2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureeventlog',
            index=models.Index(fields=['signature_request', '-received_at'], name='signature_s_signatu_072e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureeventlog',
            index=models.Index(fields=['event_type', 'processed'], name='signature_s_event_t_ec8f42_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureeventlog',
            index=models.Index(fields=['provider_event_type'], name='signature_s_provide_96d19d_idx'),
        ),
    ]
